# Generated by Django 4.2.1 on 2023-05-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=255, unique=True, verbose_name='Кітап атауы')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('photo', models.ImageField(upload_to='img', verbose_name='Фото')),
                ('desc', models.CharField(max_length=255, verbose_name='Сипаттамасы')),
                ('genre', models.CharField(max_length=255, verbose_name='Жанр')),
                ('price', models.IntegerField(verbose_name='Бағасы')),
                ('pieces', models.IntegerField(verbose_name='Дана')),
            ],
        ),
    ]
