# Generated by Django 4.2.1 on 2023-05-18 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=255, unique=True, verbose_name='Кітап атауы')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('photo', models.ImageField(upload_to='img', verbose_name='Фото')),
                ('desc', models.CharField(max_length=1024, verbose_name='Сипаттамасы')),
                ('genre', models.CharField(max_length=255, verbose_name='Жанр')),
                ('price', models.IntegerField(verbose_name='Бағасы')),
                ('pieces', models.IntegerField(verbose_name='Дана')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=1024)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('address', models.CharField(max_length=30, verbose_name='Мекен жайы')),
                ('city', models.CharField(max_length=20, verbose_name='Қала')),
                ('arrived', models.BooleanField(default=False)),
                ('returned', models.BooleanField(default=False)),
                ('buyers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposite', models.IntegerField(default=0)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
