# Generated by Django 4.2.1 on 2023-05-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.CharField(max_length=1024, verbose_name='Сипаттамасы'),
        ),
    ]
