# Generated by Django 4.2.1 on 2023-05-17 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
