# Generated by Django 4.2.1 on 2023-05-17 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_address_order_city_alter_order_due_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
