# Generated by Django 4.2.1 on 2023-05-17 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arrived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=30, verbose_name='Мекен жайы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=20, verbose_name='Қала'),
        ),
    ]
