# Generated by Django 4.2.1 on 2023-05-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_order_arrived_alter_order_address_alter_order_buyers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateField(),
        ),
    ]
