# Generated by Django 4.2.1 on 2023-05-18 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_order_returned'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
