# Generated by Django 4.2.1 on 2023-05-18 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=500)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('address', models.CharField(max_length=30, verbose_name='Мекен жайы')),
                ('city', models.CharField(max_length=20, verbose_name='Қала')),
                ('arrived', models.BooleanField(default=False)),
                ('returned', models.BooleanField(default=False)),
                ('buyers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
