# Generated by Django 4.2.1 on 2023-05-18 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_order_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
